Improve service script

diff --git a/pdisk-server/rpm/src/main/scripts/pdisk b/pdisk-server/rpm/src/main/scripts/pdisk
--- a/pdisk-server/rpm/src/main/scripts/pdisk
+++ b/pdisk-server/rpm/src/main/scripts/pdisk
@@ -556,7 +556,21 @@ case "$ACTION" in
     ;;
 esac
     
+sleep 1
+
 ## ZooKeeper management
+echo -n "Trying to $ACTION ZooKeeper service... "
 /bin/sh $ZOOKEEPER_SERVER_CMD $ACTION &>> /var/log/zookeeper.log
+[ $? -gt 0 ] && echo "FAILED" || echo "OK"
+
+## Start tgtd if not
+if [ "x$ACTION" = "xstart" ]
+then
+    TGT_SERV="/sbin/service tgtd"
+
+    $TGT_SERV status &>/dev/null
+
+    [ $? -gt 0 ] && $TGT_SERV start 
+fi
 
 exit 0
