use latest init.d script

diff --git a/pdisk-server/rpm/src/main/scripts/pdisk b/pdisk-server/rpm/src/main/scripts/pdisk
--- a/pdisk-server/rpm/src/main/scripts/pdisk
+++ b/pdisk-server/rpm/src/main/scripts/pdisk
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/usr/bin/env bash  
 #
 # Startup script for jetty under *nix systems (it works under NT/cygwin too).
 
@@ -12,19 +12,19 @@
 # Configuration files
 #
 # /etc/default/jetty
-#   If it exists, this is read at the start of script. It may perform any
+#   If it exists, this is read at the start of script. It may perform any 
 #   sequence of shell commands, like setting relevant environment variables.
 #
 # $HOME/.jettyrc
-#   If it exists, this is read at the start of script. It may perform any
+#   If it exists, this is read at the start of script. It may perform any 
 #   sequence of shell commands, like setting relevant environment variables.
 #
 # /etc/jetty.conf
 #   If found, and no configurations were given on the command line,
-#   the file will be used as this script's configuration.
+#   the file will be used as this script's configuration. 
 #   Each line in the file may contain:
 #     - A comment denoted by the pound (#) sign as first non-blank character.
-#     - The path to a regular file, which will be passed to jetty as a
+#     - The path to a regular file, which will be passed to jetty as a 
 #       config.xml file.
 #     - The path to a directory. Each *.xml file in the directory will be
 #       passed to jetty as a config.xml file.
@@ -34,7 +34,7 @@
 # $JETTY_HOME/etc/jetty.xml
 #   If found, used as this script's configuration file, but only if
 #   /etc/jetty.conf was not present. See above.
-#
+#   
 # Configuration variables
 #
 # JAVA
@@ -52,7 +52,7 @@
 #
 #    <Arg><Property name="jetty.home" default="."/>/webapps/jetty.war</Arg>
 #
-# JETTY_PORT
+# JETTY_PORT (Deprecated - use JETTY_ARGS)
 #   Override the default port for Jetty servers. If not set then the
 #   default value in the xml configuration file will be used. The java
 #   system property "jetty.port" will be set to this value for use in
@@ -68,14 +68,16 @@
 #
 # JETTY_RUN
 #   Where the jetty.pid file should be stored. It defaults to the
-#   first available of /var/run, /usr/var/run, JETTY_HOME and /tmp
+#   first available of /var/run, /usr/var/run, JETTY_HOME and /tmp 
 #   if not set.
-#
+#  
 # JETTY_PID
 #   The Jetty PID file, defaults to $JETTY_RUN/jetty.pid
-#
+#   
 # JETTY_ARGS
 #   The default arguments to pass to jetty.
+#   For example
+#      JETTY_ARGS=jetty.port=8080 jetty.spdy.port=8443 jetty.secure.port=443
 #
 # JETTY_USER
 #   if set, then used as a username to run the server as
@@ -83,7 +85,7 @@
 
 usage()
 {
-    echo "Usage: ${0##*/} [-d] {start|stop|run|restart|check|status|supervise} [ CONFIGS ... ] "
+    echo "Usage: ${0##*/} [-d] {start|stop|run|restart|check|supervise} [ CONFIGS ... ] "
     exit 1
 }
 
@@ -98,10 +100,10 @@ findDirectory()
   local L OP=$1
   shift
   for L in "$@"; do
-    [ "$OP" "$L" ] || continue
+    [ "$OP" "$L" ] || continue 
     printf %s "$L"
     break
-  done
+  done 
 }
 
 running()
@@ -109,6 +111,24 @@ running()
   local PID=$(cat "$1" 2>/dev/null) || return 1
   kill -0 "$PID" 2>/dev/null
 }
+
+started()
+{
+  # wait for 60s to see "STARTED" in PID file, needs jetty-started.xml as argument
+  for T in 1 2 3 4 5 6 7 9 10 11 12 13 14 15 
+  do
+    sleep 4
+    [ -z "$(grep STARTED $1 2>/dev/null)" ] || return 0
+    [ -z "$(grep STOPPED $1 2>/dev/null)" ] || return 1
+    [ -z "$(grep FAILED $1 2>/dev/null)" ] || return 1
+    local PID=$(cat "$2" 2>/dev/null) || return 1
+    kill -0 "$PID" 2>/dev/null || return 1
+    echo -n ". "
+  done
+
+  return 1;
+}
+
 
 readConfig()
 {
@@ -134,11 +154,23 @@ done
 ACTION=$1
 shift
 
+
 ##################################################
-# Read pdisk configuration file
+# Set the default user to run the daemon
 ##################################################
-for CONFIG in /etc/default/pdisk; do
-  if [ -f "$CONFIG" ] ; then
+JETTY_USER=slreg
+
+##################################################
+# Read any configuration files
+##################################################
+ETC=/etc
+if [ $UID != 0 ]
+then 
+  ETC=$HOME/etc
+fi
+
+for CONFIG in $ETC/default/pdisk; do
+  if [ -f "$CONFIG" ] ; then 
     readConfig "$CONFIG"
   fi
 done
@@ -147,7 +179,7 @@ done
 ##################################################
 # Set tmp if not already set.
 ##################################################
-TMPDIR=${TMPDIR:-/var/lib/stratuslab}
+TMPDIR=${TMPDIR:-/var/lib/stratuslab/pdisk}
 mkdir -p $TMPDIR
 
 ##################################################
@@ -155,31 +187,34 @@ mkdir -p $TMPDIR
 ##################################################
 JETTY_INSTALL_TRACE_FILE="etc/jetty.xml"
 
+
 ##################################################
 # Try to determine JETTY_HOME if not set
 ##################################################
-if [ -z "$JETTY_HOME" ]
+if [ -z "$JETTY_HOME" ] 
 then
   JETTY_SH=$0
   case "$JETTY_SH" in
-    /*)   ;;
-    ./*)  ;;
-    *)    JETTY_SH=./$JETTY_SH ;;
+    /*)     JETTY_HOME=${JETTY_SH%/*/*} ;;
+    ./*/*)  JETTY_HOME=${JETTY_SH%/*/*} ;;
+    ./*)    JETTY_HOME=.. ;;
+    */*/*)  JETTY_HOME=./${JETTY_SH%/*/*} ;;
+    */*)    JETTY_HOME=. ;;
+    *)      JETTY_HOME=.. ;;
   esac
-  JETTY_HOME=${JETTY_SH%/*/*}
 
-  if [ ! -f "${JETTY_SH%/*/*}/$JETTY_INSTALL_TRACE_FILE" ]
-  then
+  if [ ! -f "$JETTY_HOME/$JETTY_INSTALL_TRACE_FILE" ]
+  then 
     JETTY_HOME=
   fi
 fi
 
 
 ##################################################
-# if no JETTY_HOME, search likely locations.
+# if no JETTY_HOME, use default.
 ##################################################
 if [ -z "$JETTY_HOME" ] ; then
-  POSSIBLE_JETTY_HOME="/opt/stratuslab/storage/pdisk"
+  POSSIBLE_JETTY_HOME="/opt/stratuslab/pdisk"
   if [ -d "$POSSIBLE_JETTY_HOME" ]; then
     JETTY_HOME=$POSSIBLE_JETTY_HOME
   fi
@@ -190,7 +225,7 @@ fi
 # No JETTY_HOME yet? We're out of luck!
 ##################################################
 if [ -z "$JETTY_HOME" ]; then
-  echo "** ERROR: JETTY_HOME not set, you need to set it or install in a standard location"
+  echo "** ERROR: JETTY_HOME not set, you need to set it or install in a standard location" 
   exit 1
 fi
 
@@ -201,7 +236,7 @@ JETTY_HOME=$PWD
 #####################################################
 # Check that jetty is where we think it is
 #####################################################
-if [ ! -r "$JETTY_HOME/$JETTY_INSTALL_TRACE_FILE" ]
+if [ ! -r "$JETTY_HOME/$JETTY_INSTALL_TRACE_FILE" ] 
 then
   echo "** ERROR: Oops! Jetty doesn't appear to be installed in $JETTY_HOME"
   echo "** ERROR:  $JETTY_HOME/$JETTY_INSTALL_TRACE_FILE is not readable!"
@@ -213,11 +248,11 @@ fi
 # but only if no configurations were given on the
 # command line.
 ##################################################
-if [ -z "$JETTY_CONF" ]
+if [ -z "$JETTY_CONF" ] 
 then
-  if [ -f /etc/jetty.conf ]
+  if [ -f $ETC/jetty.conf ]
   then
-    JETTY_CONF=/etc/jetty.conf
+    JETTY_CONF=$ETC/jetty.conf
   elif [ -f "$JETTY_HOME/etc/jetty.conf" ]
   then
     JETTY_CONF=$JETTY_HOME/etc/jetty.conf
@@ -227,7 +262,7 @@ fi
 ##################################################
 # Get the list of config.xml files from jetty.conf
 ##################################################
-if [ -z "$CONFIGS" ] && [ -f "$JETTY_CONF" ] && [ -r "$JETTY_CONF" ]
+if [ -z "$CONFIGS" ] && [ -f "$JETTY_CONF" ] && [ -r "$JETTY_CONF" ] 
 then
   while read -r CONF
   do
@@ -235,18 +270,18 @@ then
       continue
     fi
 
-    if [ -d "$CONF" ]
+    if [ -d "$CONF" ] 
     then
       # assume it's a directory with configure.xml files
       # for example: /etc/jetty.d/
       # sort the files before adding them to the list of CONFIGS
       for XMLFILE in "$CONF/"*.xml
       do
-        if [ -r "$XMLFILE" ] && [ -f "$XMLFILE" ]
+        if [ -r "$XMLFILE" ] && [ -f "$XMLFILE" ] 
         then
           CONFIGS+=("$XMLFILE")
         else
-          echo "** WARNING: Cannot read '$XMLFILE' specified in '$JETTY_CONF'"
+          echo "** WARNING: Cannot read '$XMLFILE' specified in '$JETTY_CONF'" 
         fi
       done
     else
@@ -259,18 +294,25 @@ fi
 #####################################################
 # Find a location for the pid file
 #####################################################
-if [ -z "$JETTY_RUN" ]
+if [ -z "$JETTY_RUN" ] 
 then
   JETTY_RUN=$(findDirectory -w /var/run /usr/var/run $JETTY_HOME /tmp)
 fi
 
 #####################################################
-# Find a PID for the pid file
+# Find a pid and state file
 #####################################################
-if [ -z "$JETTY_PID" ]
+if [ -z "$JETTY_PID" ] 
 then
   JETTY_PID="$JETTY_RUN/pdisk.pid"
 fi
+
+if [ -z "$JETTY_STATE" ] 
+then
+  JETTY_STATE=$JETTY_HOME/jetty.state  # don't change name
+fi
+JAVA_OPTIONS+=("-Djetty.state=$JETTY_STATE")
+rm -f $JETTY_STATE
 
 ##################################################
 # Setup JAVA if unset
@@ -289,9 +331,9 @@ fi
 #####################################################
 # See if JETTY_PORT is defined
 #####################################################
-if [ "$JETTY_PORT" ]
+if [ "$JETTY_PORT" ] 
 then
-  JAVA_OPTIONS+=("-Djetty.port=$JETTY_PORT")
+  JETTY_ARGS+=("jetty.port=$JETTY_PORT")
 fi
 
 #####################################################
@@ -332,15 +374,15 @@ RUN_ARGS=(${JAVA_OPTIONS[@]} -jar "$JETTY_START" $JETTY_ARGS "${CONFIGS[@]}")
 RUN_CMD=("$JAVA" ${RUN_ARGS[@]})
 
 #####################################################
-# Comment these out after you're happy with what
+# Comment these out after you're happy with what 
 # the script is doing.
 #####################################################
 if (( DEBUG ))
 then
   echo "JETTY_HOME     =  $JETTY_HOME"
   echo "JETTY_CONF     =  $JETTY_CONF"
-  echo "JETTY_RUN      =  $JETTY_RUN"
   echo "JETTY_PID      =  $JETTY_PID"
+  echo "JETTY_START    =  $JETTY_START"
   echo "JETTY_ARGS     =  $JETTY_ARGS"
   echo "CONFIGS        =  ${CONFIGS[*]}"
   echo "JAVA_OPTIONS   =  ${JAVA_OPTIONS[*]}"
@@ -355,28 +397,20 @@ case "$ACTION" in
   start)
     echo -n "Starting Jetty: "
 
-    if (( NO_START )); then
+    if (( NO_START )); then 
       echo "Not starting jetty - NO_START=1";
       exit
     fi
 
-    if type start-stop-daemon > /dev/null 2>&1
+    if [ $UID -eq 0 ] && type start-stop-daemon > /dev/null 2>&1 
     then
       unset CH_USER
       if [ -n "$JETTY_USER" ]
       then
         CH_USER="-c$JETTY_USER"
       fi
-      if start-stop-daemon -S -p"$JETTY_PID" $CH_USER -d"$JETTY_HOME" -b -m -a "$JAVA" -- "${RUN_ARGS[@]}" --daemon
-      then
-        sleep 1
-        if running "$JETTY_PID"
-        then
-          echo "OK"
-        else
-          echo "FAILED"
-        fi
-      fi
+
+      start-stop-daemon -S -p"$JETTY_PID" $CH_USER -d"$JETTY_HOME" -b -m -a "$JAVA" -- "${RUN_ARGS[@]}" --daemon
 
     else
 
@@ -392,7 +426,7 @@ case "$ACTION" in
         fi
       fi
 
-      if [ "$JETTY_USER" ]
+      if [ "$JETTY_USER" ] 
       then
         touch "$JETTY_PID"
         chown "$JETTY_USER" "$JETTY_PID"
@@ -402,22 +436,32 @@ case "$ACTION" in
           disown \$!
           echo \$! > '$JETTY_PID'"
       else
-        nohup "${RUN_CMD[@]}" &>/dev/null &
+        "${RUN_CMD[@]}" &
         disown $!
         echo $! > "$JETTY_PID"
-        sleep 3
       fi
 
-      echo "STARTED Jetty `date`"
+    fi
+
+    if expr "${CONFIGS[*]}" : '.*etc/jetty-started.xml.*' >/dev/null
+    then
+      if started "$JETTY_STATE" "$JETTY_PID"
+      then
+        echo "OK `date`"
+      else
+        echo "FAILED `date`"
+      fi
+    else
+      echo "ok `date`"
     fi
 
     ;;
 
   stop)
     echo -n "Stopping Jetty: "
-    if type start-stop-daemon > /dev/null 2>&1; then
+    if [ $UID -eq 0 ] && type start-stop-daemon > /dev/null 2>&1; then
       start-stop-daemon -K -p"$JETTY_PID" -d"$JETTY_HOME" -a "$JAVA" -s HUP
-
+      
       TIMEOUT=30
       while running "$JETTY_PID"; do
         if (( TIMEOUT-- == 0 )); then
@@ -432,7 +476,7 @@ case "$ACTION" in
     else
       PID=$(cat "$JETTY_PID" 2>/dev/null)
       kill "$PID" 2>/dev/null
-
+      
       TIMEOUT=30
       while running $JETTY_PID; do
         if (( TIMEOUT-- == 0 )); then
@@ -488,25 +532,24 @@ case "$ACTION" in
     fi
 
     exec "${RUN_CMD[@]}"
-
     ;;
 
   check|status)
     echo "Checking arguments to Jetty: "
+    echo "START_INI      =  $START_INI"
     echo "JETTY_HOME     =  $JETTY_HOME"
     echo "JETTY_CONF     =  $JETTY_CONF"
-    echo "JETTY_RUN      =  $JETTY_RUN"
     echo "JETTY_PID      =  $JETTY_PID"
-    echo "JETTY_PORT     =  $JETTY_PORT"
+    echo "JETTY_START    =  $JETTY_START"
     echo "JETTY_LOGS     =  $JETTY_LOGS"
-    echo "START_INI      =  $START_INI"
     echo "CONFIGS        =  ${CONFIGS[*]}"
-    echo "JAVA_OPTIONS   =  ${JAVA_OPTIONS[*]}"
-    echo "JAVA           =  $JAVA"
     echo "CLASSPATH      =  $CLASSPATH"
+    echo "JAVA           =  $JAVA"
+    echo "JAVA_OPTIONS   =  ${JAVA_OPTIONS[*]}"
+    echo "JETTY_ARGS     =  $JETTY_ARGS"
     echo "RUN_CMD        =  ${RUN_CMD[*]}"
     echo
-
+    
     if [ -f "$JETTY_PID" ]
     then
       echo "Jetty running pid=$(< "$JETTY_PID")"
